### ISSUE TITLE
Possible to update the result to include FAERS 2015q4 data?

### ISSUE THREAD

**Issue by zhiboz** [dbuijs/faers2csv#3]
Thanks a lot to share the result at https://zenodo.org/record/45589! Is it feasible to update the results there to include the FAERS 2015q4 data as well?

**Comment by dbuijs** [comment]
There is a cost to processing the whole dataset (it takes about 3 hours with 20 cores and 64 GB RAM), and I haven't yet gotten around to figuring out how to verify an incremental update, and the US FDA explicitly indicates that they might change stuff, so until I figure out how to do this (perhaps with hashes on the json files), I'll need to reprocess the whole thing. 

At some point I'll probably do it, but it's not a high priority for me right now. I published the scripts so that interested people can run them themselves. I'm sure the community would really appreciate it if you took it upon yourself to run the scripts and publish the results.
